### ISSUE TITLE
Add a pure 'ponyfill' export

### ISSUE THREAD

**Issue by Siilwyn** [mkay581/cookie-store#77]
What do you think of also exporting a [ponyfill](https://github.com/sindresorhus/ponyfill) alternative? Basically purely mimicking the cookie store API without using it.

**Comment by mkay581** [comment]
Hmm my thinking was that consumers would want the best performance in modern browsers by using the native cookie store API. Are there any benefits you see from having a ponyfill vs not? Or any specific use cases you have in mind?

**Comment by Siilwyn** [comment]
Would like to use this package without it changing global things, in general, you should not modify API's you don't own. My use case would be to use this package until the new Cookie Store API becomes available in the other evergeen browsers: Not really interested in the performance side but just more using an API in my code that won't have to change dramatically in the future, so migrating becomes easy.

**Comment by mkay581** [comment]
> you should not modify API's you don't own

There may be a misunderstanding of what this package does. It doesn't modify any API. It simply [detects if `window.cookieStore` is defined and if not sets it to the API of this package](https://github.com/mkay581/cookie-store/blob/master/index.ts#L312-L314).

> using an API in my code that won't have to change dramatically in the future, so migrating becomes easy

That's exactly what this package aims to do. Because it's a polyfill, you can essentially remove this package entirely once you don't need to support IE 11 or lower without changing any code. But the CookieStore API is not actually final yet so using it this early will probably require changes to your code regardless of whether you use this package or not. I would suggest maybe avoid using CookieStore API until it's more stable if the intention is to not use the native CookieStore API. There are a lot of cookie packages that are available that are more in line with your goals.

**Comment by Siilwyn** [comment]
No I understand what this package does, it's expected polyfill behavior.

Also understand that since the API spec is still in motion I might have to change but at least I can just follow package updates.
Your point about this and support for old browsers is actually a good example where things can go wrong with a polyfill but not with a ponyfill: if an existing API method gets renamed before this package does, code on new browsers will break.

**Comment by mkay581** [comment]
> if an existing API method gets renamed before this package does, code on new browsers will break.

That's only a problem for polyfills that have nothing to do with the spec. Because CookieStore API is a specification, once it is final, it will never change and a method would never be renamed. As it stands now, this API will only be applied on browsers that do not support the CookieStore API _at all_ natively -- not modern browsers. So modern browsers will be unaffected by any change in this package.
